-- 코드를 입력하세요 서브쿼리
SELECT MONTH(START_DATE) as MONTH, CAR_ID,count(HISTORY_ID) as RECORDS 
from CAR_RENTAL_COMPANY_RENTAL_HISTORY
where START_DATE between "2022-08-01" and "2022-10-31"
 and CAR_ID IN(    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN "2022-08-01" AND "2022-10-31"
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5)
group by CAR_ID,MONTH
order by MONTH,CAR_ID desc;